  AWSTemplateFormatVersion: '2010-09-09'
  Transform: AWS::Serverless-2016-10-31
  Description: AWS Serverless Quarkus HTTP - application-acount-preference-1.0.0-SNAPSHOT
  Globals:
    Api:
      EndpointConfiguration: REGIONAL
      BinaryMediaTypes:
        - "*/*"

  Resources:
    ApiPreferenceNative:
      Type: AWS::Serverless::Function
      Properties:
        FunctionName: lambda-application-preference
        Handler: not.used.in.provided.runtimei
        Runtime: provided.al2023
        CodeUri: target/function.zip
        MemorySize: 128
        Policies:
          - AWSLambdaBasicExecutionRole
          - AmazonDynamoDBFullAccess
        Timeout: 15
        Environment:
          Variables:
            DISABLE_SIGNAL_HANDLERS: true
        Events:
          GetResource:
            Type: Api
            Properties:
              Path: /{proxy+}
              Method: any

  Outputs:
    ApiProfileApi:
      Description: URL for application
      Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/'
      Export:
        Name: lambda-application-preference
